
server:
  port: 8000
  servlet: 
    context-path: /
    
spring:
  datasource:
#   6.0미만 버전은 url:jdbc:mysql://localhost:3306/white ,driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/white?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: white
    password: bitc5600
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
#     PhysicalNamingStrategyStandardImpl 변수명을 대소문자 그대로 만들어줌
#     SpringPhysicalNamingStrategy 변수명을 create_date 형식으로 만들어줌     
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true
      
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      